### PR TITLE
fix(ui): styles for email compose form

### LINKED ISSUE #291: fix styles for email compose
- [x] For “New message” text change font-size to 16px and font-weight to 500 as in other cards
- [x] For “To:”/”Cc:”/”Bcc:” text change color to tblr-gray-800
- [x] For text area: change placeholder text color to tblr-gray-400
- [x] For container
  - [x] Change spacing (paddings) to be as in [mockup](https://www.figma.com/design/kQOH4s5DnfWL0p6o6tlMQz/Draft-%5BATS%5D?node-id=2135-4743&node-type=canvas&t=cQKTlFHB4AD4iaS2-0)
- [x] For “Send” button: change size from Tiny to Small (32px)
- [x] Nice-to-have: For Cc/Bcc list email options in alphabetical order

### PR DESCRIPTION
**Pull request by wrmk**
Closes #291.

- [x] I have reviewed my code in "Files changed" tab.
- [x] I have re-read the issue and this PR fully resolves it.

### CODE REVIEW

File: app/assets/javascript/controllers/input_utils_controller.js
Comment (wrmk) [inline app/assets/javascript/controllers/input_utils_controller.js:1]: forgot to copy this controller, allow to ctrl+v URLs into rich text

File: app/assets/javascript/controllers/enter_turbo_submit_controller.js
Comment (wrmk) [inline app/assets/javascript/controllers/enter_turbo_submit_controller.js:1]: part of fixing problem with disabled enter in rich text area if "to" field is empty

File: app/assets/javascript/src/shared/input_utils.js
Comment (wrmk) [inline app/assets/javascript/src/shared/input_utils.js:1]: part of fixing problem with not working enter in rich text area if "to" field is empty

File: app/assets/javascript/controllers/select_component_controller.js [hunk 1]
```diff
@@ -140,7 +141,8 @@ export default class SelectComponentController extends Controller {
   // It may happen when we type something irrelevant and press enter.
   #restrictEnterKeyIfNoneSelected(target) {
     target.form.onkeydown = (e) => {
-      if (e.key === "Enter" && target.selectize.items.length === 0) {
+      // Don't prevent default 'enter' behaviour for rich text areas.
+      if (e.key === "Enter" && target.selectize.items.length === 0 && !eventFromRichText(e)) {
```
[the remark this answers is not in the document]
Comment (wrmk) [reply app/assets/javascript/controllers/select_component_controller.js:145]: same problem in the internal project too, will create PR

[the remark this answers is not in the document]
Comment (wrmk) [reply app/assets/javascript/controllers/select_component_controller.js:145]: https://github.com/toughbyte/hub/pull/15910
