### PR TITLE
fix: order on task grid

### LINKED ISSUE #91: Fix tasks grid sorting
**How it works**
The sorting arrows for specific fields on the item grid simply reload the page and do not apply sorting

**How it should work**
Sorting arrows should sort rows by a column value.

This may not be the only broken grid.

**How to reproduce**

1. Open tasks grid
2. Click the sorting arrow next to any column

### PR DESCRIPTION
**Pull request by Lyams**
Closes #91.

- [x] I have reviewed my code in "Files changed" tab.
- [x] I have re-read the issue and this PR fully resolves it.

### CODE REVIEW

File: app/grids/ats/tasks_grid.rb [hunk 1]
```diff
@@ -144,7 +144,9 @@ class ATS::TasksGrid
     :assignee,
     html: true,
     preload: { assignee: :account },
-    order: ->(scope) { scope.joins(assignee: :account).group("accounts.id").order("accounts.name") }
+    order: ->(scope) {
+             scope.left_outer_joins(assignee: :account).group("accounts.id").order("accounts.name")
```
Comment (Lyams) [inline app/grids/ats/tasks_grid.rb:148]: Setting the order by this field removed tasks without assignee from the search.

**Comment by PrinceYauj** [comment]
@Lyams, I've gone through some grids and clicked the order buttons and noticed that 
candidate (john doe) -> tasks tab -> assignee column sorting is also broken and the problem is still there on your branch. Do you think it will be reasonable to fix it in this issue, or do we need to create another one?
image

File: app/grids/ats/profile_tasks_grid.rb [hunk 2]
```diff
@@ -49,7 +49,9 @@ class ATS::ProfileTasksGrid
     :assignee,
     html: true,
     preload: { assignee: :account },
-    order: ->(scope) { scope.joins(assignee: :account).group("account.id").order("accounts.name") }
+    order: ->(scope) {
+             scope.left_outer_joins(assignee: :account).group("accounts.id").order("accounts.name")
+           }
```
Comment (Lyams) [inline app/grids/ats/profile_tasks_grid.rb:54]: Setting the order by this field removed tasks without assignee from the search.
And fixed typo:  `group("accounts.id")` instead of `group("account.id")`

**Review by PrinceYauj — APPROVED** [review]
