### PR TITLE
fix(career site): correctly upload cv file when candidate applies on position

### LINKED ISSUE #14: File isn't uploaded when candidate applied via career site
How it works
When candidate applied, the file is visible on it's profile but not added to the amazon

How it should work
File should be uploaded to amazon

### PR DESCRIPTION
**Pull request by wrmk**
Closes #14.

- [x] I have reviewed my code in "Files changed" tab.
- [x] I have re-read the issue and this PR fully resolves it.

### CODE REVIEW

File: app/operations/candidates/apply.rb [hunk 1]
```diff
@@ -54,7 +54,16 @@ def call
...
+      candidate
+    end
+
+    # File uploading did not work correctly inside the main transaction.
+    case Candidates::UploadFile.new(candidate:, actor_account:, file:, cv: true).call
+    in Success(_)
       Success()
+    in Failure[:file_invalid, e]
+      candidate.destroy!
+      Failure[:file_invalid, e]
```
Comment (wrmk) [inline app/operations/candidates/apply.rb:66]: [discussion](https://toughbyte.slack.com/archives/C066V39GZPT/p1730798864887389?thread_ts=1730527148.486689&cid=C066V39GZPT) where agreed to move file uploading out from the main transaction and imitate rollback if file was not uploaded

File: app/controllers/api/v1/documents_controller.rb [hunk 2]
```diff
@@ -18,7 +18,7 @@ def create
         case add_resume(candidate, file)
         in Success(file)
           render json: { url: candidate.url }, status: :ok
-        in Failure[:validation_failed, e]
```
Comment (wrmk) [inline app/controllers/api/v1/documents_controller.rb:21]: become unused because we do not upload file via candidates::add operation

File: app/controllers/ats/candidates_controller.rb [hunk 3]
```diff
@@ -226,8 +226,6 @@ def create
                   notice: t("candidates.candidate_created")
     in Failure[:candidate_invalid, candidate]
       redirect_to ats_candidates_path, alert: candidate.errors.full_messages
-    in Failure[:validation_failed, e]
```
Comment (wrmk) [inline app/controllers/ats/candidates_controller.rb:229]: become unused because we do not upload file via candidates::add operation

**Review by ksnitsky — APPROVED** [review]
Rename the PR on merge to main, please
