### PR TITLE
fix: fixes position page events logic after applying

### LINKED ISSUE #23: Career site fixes: Position page - events logic after applying
**Problem**
On Career site, Position page we have several issues with events after submitted application form:

- Candidate is initially assigned to FreeATS, then reassigned to the responsible recruiter

CleanShot 31 10 2024 at 14-54

- Incorrect event for placement “FreeATS assigned the candidate to POSITION”
- Missing “ACTOR_USER added the candidate using extension” event

**Solution**
- Candidate should be assigned to the responsible recruiter initially
- Event for placement should be “The candidate applied to POSITION”
- Add “ACTOR_USER added the candidate using extension” event

### PR DESCRIPTION
**Pull request by Lyams**
Closes #23.

- [x] I have reviewed my code in "Files changed" tab.
- [x] I have re-read the issue and this PR fully resolves it.

### CODE REVIEW

File: app/operations/candidates/add.rb [hunk 1]
```diff
@@ -38,14 +24,30 @@ class Candidates::Add < ApplicationOperation
         type: Types::Strict::String
       ).optional
     ),
+    file_id_to_change_cv_status?: Types::Strict::String,
```
Comment (delavaler) [inline app/operations/candidates/add.rb:27]: Do we need this property? The same for file_id_to_remove/remove_avatar?

File: app/helpers/candidates_helper.rb [hunk 2]
```diff
@@ -17,15 +17,24 @@ def candidate_display_activity(event)
     actor_account_name = compose_actor_account_name(event)
 
     text =
-      if event.type == "email_received"
+      if event.type == "placement_added" && event.properties["self_applied"] == true
```
[the remark this answers is not in the document]
Comment (amgalanbadmaev) [reply app/helpers/candidates_helper.rb:20]: Screenshot didn't load @delavaler

[the remark this answers is not in the document]
Comment (delavaler) [reply app/helpers/candidates_helper.rb:20]: No, the difference is that on first we use "candidate applied ..." to show event about adding candidate to the database, and ordinar event about assigning on the position
While on second we use "FreeATS added candidate manually" to show event about adding candidate to the database, but rewrite assigning candidate on position as "Candidate applied.."

File: app/helpers/candidates_helper.rb [hunk 3]
```diff
@@ -17,102 +17,143 @@ def candidate_display_activity(event)
     actor_account_name = compose_actor_account_name(event)
 
     text =
-      if event.type == "email_received"
-        []
-      else
-        [actor_account_name]
-      end
```
Comment (Lyams) [inline app/helpers/candidates_helper.rb:24]: This code also started to branch more and more. I don't like it.
I tried changing it. But without tests it looked dangerous. So I added tests too.

File: app/operations/candidates/add.rb (hunk 1 above)
Comment (Lyams) [reply app/operations/candidates/add.rb:27]: You are right.  I don't see these arguments being passed to the operation and used in it.

Comment (Lyams) [reply app/operations/candidates/add.rb]: Fixed in [58ab709](https://github.com/freeats/freeats/pull/103/commits/58ab70999ea21bb6ff9e03405311ebf6f4818e4d)

File: app/helpers/candidates_helper.rb [hunk 4]
```diff
@@ -16,110 +16,152 @@ def ats_candidate_duplicates_merge_association_select(form, form_field_name, opt
   def candidate_display_activity(event)
     actor_account_name = compose_actor_account_name(event)
 
+    # rubocop:disable Layout/IndentationWidth
```
[the remark this answers is not in the document]
Comment (Lyams) [reply app/helpers/candidates_helper.rb]: Solved.

File: app/helpers/candidates_helper.rb [hunk 5]
```diff
@@ -17,102 +17,143 @@ def candidate_display_activity(event)
...
-      if event.type == "email_received"
-        []
-      else
-        [actor_account_name]
-      end
-    text <<
       case event.type
       when "candidate_added"
-        "added the candidate"
+        if event.properties["method"] == "manual" && event.actor_account_id.present?
```
Comment (delavaler) [inline app/helpers/candidates_helper.rb:22]: Can we just add another method if candidate applies instead of this condition? it could be "applied" or "career site".
With this code it's unclear why it was added, also, later it will help build stats.

File: app/helpers/candidates_helper.rb (hunk 2 above)
[the remark this answers is not in the document]
Comment (delavaler) [reply app/helpers/candidates_helper.rb]: @amgalanbadmaev , @Lyams  aren't we agree to not show "manually" whne FreeATS added the candidate since "manually" on this case doesn't make sence?

File: app/helpers/candidates_helper.rb [hunk 6]
```diff
@@ -17,102 +17,143 @@ def candidate_display_activity(event)
...
-      if event.type == "email_received"
-        []
-      else
-        [actor_account_name]
-      end
-    text <<
       case event.type
       when "candidate_added"
-        "added the candidate"
+        if event.properties["method"].in?(%w[manual applied])
```
Comment (delavaler) [inline app/helpers/candidates_helper.rb:22]: Looks like we mixed the initial idea and result of discussion. On the call we agreed to not show "manually" when candidate applied, since "FreeATS added manually" doesn't make sence

File: app/helpers/candidates_helper.rb (hunk 2 above)
[the remark this answers is not in the document]
Comment (amgalanbadmaev) [reply app/helpers/candidates_helper.rb]: Yes, discussed on daily call.

**Review by delavaler — APPROVED** [review]

File: test/helpers/candidates_helper_test.rb [hunk 7]
```diff
@@ -0,0 +1,262 @@
...
+    @event.type = "candidate_added"
+    @event.properties = { "method" => "manual" }
+    @event.actor_account = accounts(:admin_account)
+
+    result = candidate_display_activity(@event)
+
+    assert_match("<span><b>#{@event.actor_account.name}</b> added the candidate manually</span>", result)
+  end
+
+  test "candidate_display_activity with candidate_added, method applied and actor_account_id blank" do
```
Comment (delavaler) [inline test/helpers/candidates_helper_test.rb:26]:
```suggestion
  test "candidate_display_activity with candidate_added and method applied" do
```

**Review by delavaler — APPROVED** [review]
